config/routes.rb
OhIyeah::Application.routes.draw do

  root 'home#index'

  get 'iyeah'  => "home#iyeah"
  get 'login'  => "home#login"
  get 'logout' => "home#logout"

  get '/facebook/oauth'    => "facebook#oauth",    :as => :facebook_oauth
  get '/facebook/callback' => "facebook#callback", :as => :facebook_callback

  get ':facebook_id' => "home#mypage", :as => :mypage

end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  has_many :goods

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos
  has_many :goods
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
# -*- coding: utf-8 -*-
class BaseController < ApplicationController
  def logged_in?
    !current_user.blank?
  end

  def facebook_oauth_required
    redirect_to login_path and return false if !logged_in?
  end

  def current_user
    current_user = User.where(facebook_id: facebook_user['id']).first
  end

  # facebook user を取得
  def facebook_user
    graph = Koala::Facebook::API.new(session[:facebook_access_token])
    begin
      result = graph.get_object("/me/?locale=#{get_locale}")
      return (result=='false' ? {} : result)
    rescue Exception=>e
      return {}
    end
  end

  private

  # 表示言語を切り替える
  def set_locale
    I18n.locale = get_locale
  end

  def get_locale
    session[:locale] ||= I18n.default_locale
  end

  # 表示テンプレートをスマートフォン用に切り替える
  def set_smartphone_format
    request.format = :smartphone if request.smart_phone? && !request.mobile.tablet?
  end
end

app/controllers/facebook_controller.rb
# -*- coding: utf-8 -*-
class FacebookController < BaseController
  def oauth
    oauth = Koala::Facebook::OAuth.new(Facebook::APP_ID, Facebook::SECRET, Facebook::CALLBACK_URL)
    redirect_to oauth.url_for_oauth_code(:permissions => ['user_photos'] )
  end

  def callback
    oauth = Koala::Facebook::OAuth.new(Facebook::APP_ID, Facebook::SECRET, Facebook::CALLBACK_URL)
    if params[:code]
      session[:facebook_access_token] = oauth.get_access_token(params[:code])

      if !(user = User.where(facebook_id: facebook_user['id']).first)
        user = User.new(
          facebook_id: facebook_user['id'],
          name: facebook_user['name'],
        )
        user.save
      end

      begin
        # Photo.tagged
        user = User.where(facebook_id: facebook_user['id']).first

        graph = Koala::Facebook::API.new(session[:facebook_access_token])

        result = graph.fql_query("SELECT pid, object_id, src, src_big, created FROM photo where pid in (SELECT pid FROM photo_tag  WHERE subject =  me() limit 5000)")
        result.each do |photo|
          next if Photo.where(facebook_pid: photo["pid"]).first

          user.photos.create(
            facebook_pid: photo["pid"],
            facebook_objid: photo["object_id"],
            thumbnail_url: photo["src"],
            url: photo["src_big"],
          )
        end
      end
    else
      # TODO : ERROR HANDLING
      flash[:error] = 'facebookログインに失敗しました'
      redirect_to :root and return
    end
    redirect_to mypage_path(user.facebook_id)
  end
end

app/controllers/home_controller.rb
# -*- coding: utf-8 -*-
class HomeController < BaseController
  before_action :facebook_oauth_required, :only => [:iyeah]

  def index
  end

  def login
    flash[:notice] = "facebookのログインが必要です"

    redirect_to :root
  end

  def logout
    reset_session
    redirect_to :root
  end

  def mypage

    flash[:notice] = "facebookログインが必要です" and redirect_to login_path if !User.where(facebook_id: params[:facebook_id]).first

    @user = User.where(facebook_id: params[:facebook_id]).first
    @url = "http://www.facebook.com/dialog/feed? app_id=#{Facebook::APP_ID}&link=http://oh-iyeah.konboi.com/#{params[:facebook_id]}&picture=http://oh-iyeah.konboi.com/img/icon.png&name=Oh!遺影&description=最後にみんなに見てもらう写真だからこそ、みんなが自分らしいと思う写真にしたい。素の自分、意外な自分、いつもの自分 そんな自分をみんなで選ぼう&redirect_uri=http://oh-iyeah.konboi.com/#{params[:facebook_id]}"
  end

  def iyeah
    user = User.where(facebook_id: facebook_user['id']).first

    flash[:error] = "1人1Oh!遺影 になります。ご了承ください。 " and  redirect_to mypage_path(params[:facebook_id]) and return if Good.where(photo_id: params[:photo_id]).where(user_id: user.id).first

    user.goods.create(photo_id: params[:photo_id])
    redirect_to mypage_path(params[:facebook_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
  def logged_in?
    controller.logged_in?
  end

  def current_user
    controller.current_user
  end
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="span10 offset1">
  <div class="row">
    <div class="span10">
      <blockquote>
      <p class="read"><em><b>遺影</b>:遺影（いえい）とは、物故者を偲ぶために、作られる写真もしくは、肖像画。</em><br>
        本来は自分の気に入った写真を用意すべきだが大半が旅行や結婚式などに参加した時の集合写真などからの拡大・修正が多い。<br>
        今後は、デジタルカメラなどのデータで残された場合、家族が見つけることも困難である事から、後世に残す重要な写真として確実に保存する必要性がある。
      </p>
      <p class="text-right">from <em><b>Wikipedia</b></em></p>
      </blockquote>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="span10">
      <p class="text-center">最後にみんなに見てもらう写真だからこそ、みんなが自分らしいと思う写真にしたい</p>
      <p class="text-center">素の自分、意外な自分、いつもの自分 そんな自分をみんなで選ぼう</p>
      <p class="text-center">そして声高らかに叫ぼう<b><em>Oh! Yeah</em></b></p>
    </div>
  </div>

  <% if !logged_in? %>
    <div class="row">
      <div class="span10">
        <p class="text-center"><a href="<%= facebook_oauth_path %>"><input type="button" class="btn btn-primary btn-large" value="facebook認証してはじめる"></a></p>
      </div>
    </div>
  <% end %>

</div>

app/views/home/mypage.html.erb
<div class="span12">
  <p class="text-right" style="position:fixed; top:80px; right:200px"><a href="<%= @url %>"><input type="button" class="btn btn-info" value="シェアする"></a></p>
</div>

<div class="span12">
  <% @user.photos.each do |photo| %>
    <div class="span2">
      <div>
        <p><a href="#modal<%= photo.id  %>" data-toggle="modal"><img src="<%= photo.thumbnail_url %>"></a></p>
      </div>
    </div>

    <div id="modal<%= photo.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-body">
        <p><img src="<%= photo.url %>" class="large"></p>
      </div>
      <div class="modal-footer">
        <p>Oh!遺影数: <%= photo.goods.length %></p>
        <a href="<%= iyeah_path(photo_id: photo.id, facebook_id: @user.facebook_id) %>"><button class="btn btn-primary">Oh!遺影</button></a>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" sizes="16x16" href="/favicon.ico" />
    <title><%= content_for?(:title) ? yield(:title) : "OhIyeah" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Oh!遺影</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if logged_in?  %>
                <li><%= link_to "マイページ", mypage_path(current_user.facebook_id)  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <br><br><br><br>
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Konboi</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>